"""Update system settings table

Revision ID: 75259a57969d
Revises: 1cce31ce23be
Create Date: 2024-11-20 21:55:11.490226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75259a57969d'
down_revision = '1cce31ce23be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['key'])
        batch_op.create_foreign_key(None, 'staff', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')
        batch_op.drop_column('value')
        batch_op.drop_column('key')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
